pelcro-inc/react-pelcro-js

- src/Components/PelcroModalController/PelcroModalController.service.js
- src/utils/utils.js
- URL trigger for one-off quick purchases where we pass a single SKU and start the checkout flow
- URL trigger for a cart where we pass multiple SKUs and display the cart view
> feat(url triggers): add items to cart and quickly purchase ecomm items

- src/Components/common/FacebookLoginButton/FacebookLoginButton.js
- src/Components/common/GoogleLoginButton/GoogleLoginButton.js
- allow styling social login buttons by either using props or by targeting them using the newly added CSS class names
> feat(login buttons): allow styling using props and css classes

- src/Components/PelcroModalController/PelcroModalController.service.js
- add `is_gift` url param to allow gifting offline plans
- fix `is_gift` param considering all non-empty values as `true`
> feat(url triggers): add gifting param to offline plans trigger

- .codesandbox/ci.json
> ci: add codesandbox ci config to publish test versions

- src/Components/PelcroModalController/PelcroModalController.service.js
instead of always blocking if user has a subscription, now only skipping paywall if the article is not restricted. (required a meta tag)
* feat(url triggers): add param for gifting offline plans
* fix(url triggers): 'false' being treated as true in url params
> feat(paywall): add dynamic paywall support to the controller

- src/Components/Login/LoginModal.js
This PR adds a check after a successful login if the article is restricted, if that's the case, paywall is initialized, instead of just resetting the view.
> feat(paywall): display paywall after login if article is restricted

- src/Components/AddressCreate/AddressCreateContainer.js
- src/Components/AddressSelect/AddressSelectContainer.js
- src/Components/AddressUpdate/AddressUpdateContainer.js
- src/Components/Cart/CartContainer.js
- src/Components/GiftCreate/GiftCreateContainer.js
- src/Components/GiftRedeem/GiftRedeemContainer.js
- src/Components/Login/LoginContainer.js
- src/Components/OrderCreate/OrderCreateContainer.js
- src/Components/PasswordChange/PasswordChangeContainer.js
- src/Components/PasswordForgot/PasswordForgotContainer.js
- src/Components/PasswordReset/PasswordResetContainer.js
- src/Components/PaymentCreate/PaymentCreateContainer.js
- src/Components/PaymentMethod/PaymentMethodContainer.js
- src/Components/PaymentMethodSelect/PaymentMethodSelectContainer.js
- src/Components/PaymentMethodUpdate/PaymentMethodUpdateContainer.js
- src/Components/ProfilePicChange/ProfilePicChangeContainer.js
- src/Components/Register/RegisterContainer.js
- src/Components/SubscriptionCreate/SubscriptionCreateContainer.js
- src/Components/SubscriptionRenew/SubscriptionRenewContainer.js
- src/Components/UserUpdate/UserUpdateContainer.js
- Add `pelcro-container` and container-specific CSS classes to help in targeting components using CSS selectors
> feat(containers): add CSS classes for selectors targetting

- jest.config.js
- src/Components/AddressSelect/AddressSelectSubmit.js
- src/services/Subscription/Subscription.service.test.js
test: add unit tests coverage to the subscription service
> test: add unit tests coverage to the subscription service

- src/Components/AddressCreate/AddressCreateSubmit.js
- src/Components/AddressSelect/AddressSelectSubmit.js
- src/Components/AddressUpdate/AddressUpdateSubmit.js
- src/Components/Cart/CartRemoveItemButton.js
- src/Components/GiftCreate/GiftCreateSubmitButton.js
- src/Components/GiftRedeem/GiftRedeemSubmitButton.js
- src/Components/Login/LoginButton.js
- src/Components/PasswordChange/PasswordChangeButton.js
- src/Components/PasswordForgot/PasswordForgotButton.js
- src/Components/PasswordReset/PasswordResetButton.js
- src/Components/PaymentMethod/ApplyCouponButton.js
- src/Components/PaymentMethod/CouponCode.js
- src/Components/PaymentMethod/DiscountedPrice.js
- src/Components/PaymentMethod/SubmitPaymentMethod.js
- src/Components/PaymentMethodSelect/PaymentMethodSelectSubmit.js
- src/Components/ProfilePicChange/ProfilePicChangeRemoveButton.js
- src/Components/ProfilePicChange/ProfilePicChangeSelectButton.js
- src/Components/Register/RegisterButton.js
- src/Components/Shop/ShopSelectProductButton.js
- src/Components/UserUpdate/UserUpdateButton.js
- allow overriding `className` prop for submit buttons
- allow passing props to a few subcomps that didn't have any props before
> feat: improve ability to style several comps

- src/Components/AddressCreate/AddressCreateSubmit.js
- src/Components/AddressSelect/AddressSelectSubmit.js
- src/Components/AddressUpdate/AddressUpdateSubmit.js
- src/Components/Cart/CartRemoveItemButton.js
- src/Components/GiftCreate/GiftCreateSubmitButton.js
- src/Components/GiftRedeem/GiftRedeemSubmitButton.js
- src/Components/Login/LoginButton.js
- src/Components/PasswordChange/PasswordChangeButton.js
- src/Components/PasswordForgot/PasswordForgotButton.js
- src/Components/PasswordReset/PasswordResetButton.js
- src/Components/PaymentMethod/ApplyCouponButton.js
- src/Components/PaymentMethod/CouponCode.js
- src/Components/PaymentMethod/SubmitPaymentMethod.js
- src/Components/PaymentMethodSelect/PaymentMethodSelectSubmit.js
- src/Components/ProfilePicChange/ProfilePicChangeButton.js
- src/Components/ProfilePicChange/ProfilePicChangeRemoveButton.js
- src/Components/ProfilePicChange/ProfilePicChangeSelectButton.js
- src/Components/Register/RegisterButton.js
- src/Components/Shop/ShopSelectProductButton.js
- src/Components/UserUpdate/UserUpdateButton.js
- fix buttons throwing errors because no `onClick` function is passed, and it's being called in the click handler
> fix: optional extra click handler

- src/Components/GiftCreate/GiftCreateStartDate.js
- src/SubComponents/DatePicker.js
- src/SubComponents/Tooltip.css
- src/SubComponents/Tooltip.js
- src/components.js
- src/index.css
- src/translations/en/common.json
- src/translations/en/register.json
- src/translations/fr/register.json
> feat(atoms): Add a new Tooltip atom component

- src/Components/GiftCreate/GiftCreateContainer.js
- src/Components/GiftCreate/GiftCreateStartDate.js
- src/Components/Login/LoginView.js
- src/translations/en/register.json
- src/translations/fr/register.json
> feat(gift creation): add starting date validation on the container

- public/index.html
- src/Components/Register/RegisterView.js
- src/translations/en/register.json
- src/translations/fr/register.json
- Add the ability to show the first name and last name input fields in the register modal if `window.Pelcro.uiSettings.enableNameFieldsInRegister` is set to true, this `uiSettings` object doesn't exist by default, if a client wants to enable this feature, they'll have to define it in their integration script
`      window.Pelcro.uiSettings = {
enableNameFieldsInRegister: true
};`
I personally think that this feature should not be documented, and should be given to the clients who currently need it for now, and if more clients ask for this feature, then we should add a toggle in the platform settings page, and then add it to our docs as an official feature.
>
> feat(register): add optional name fields

- src/Components/GiftCreate/GiftCreateMessage.js
- src/SubComponents/TextArea.js
- src/translations/en/register.json
- src/translations/fr/register.json
TextArea component now supports a new prop `tooltipText: string`
> feat(textarea): add tooltip text support

- src/Components/Meter/MeterModal.js
- src/Components/dashboard/DashboardOpenButton.js
- src/SubComponents/Alert.css
- src/SubComponents/Button.css
- src/SubComponents/Modal.css
- enforce having no border width for multiple buttons in UI
- enforce dashboard opening button to have a white background on hover
> fix: enforce having no border for multiple buttons

- src/Components/Meter/MeterModal.js
- src/SubComponents/Alert.css
- src/SubComponents/Button.css
- src/SubComponents/Modal.css
- add explicit styling for buttons text and background colors in all main states
> fix: enforce buttons colors

- src/Components/PaymentMethod/DiscountedPrice.js
- src/Components/PaymentMethod/PaymentMethodContainer.js
> fix(coupon): display discounted amount before taxes

- src/Components/dashboard/Dashboard.js
- close the dashboard when you click outside of it while it's open, this will only affect desktop users
> feat(dashboard): close menu when user clicks outside

- src/Components/NewsletterUpdate/NewsletterUpdateContainer.js
- src/hooks/usePelcro/pelcroActions.js
- src/translations/en/newsletter.json
- src/translations/fr/newsletter.json
- allow non logged in users to open the newsletters update modal
- wording improvements
- add success alert
> feat(url triggers): allow opening newsletters update modal for non authed users

- package.json
- rollup.config.js
- src/Components/PaymentMethod/PaymentMethodContainer.js
- src/Components/PelcroModalController/PelcroModalController.service.js
- yarn.lock
- product team wasn't ok with the loading time of the stripe SDK.
> revert: stripe sdk lazy loading

- src/translations/en/newsletter.json
- src/translations/fr/newsletter.json
> feat(newsletters update): update success wording

- src/Components/dashboard/Dashboard.js
- src/components.js
- add CSS classes to subscription action buttons in the dashboard
- export atomic alert component
> feat(dashboard): add css classes for sub action buttons

- public/index.html
- src/Components/OrderConfirm/OrderConfirmModal.js
- src/Components/PaymentMethod/DiscountedPrice.js
- src/Components/PaymentMethod/PaymentMethodContainer.js
- src/Components/PaymentMethod/SubmitPaymentMethod.js
- src/Components/PaymentMethod/TaxAmount.js
- src/Components/SubscriptionCreate/SubscriptionCreateView.js
- src/Components/common/FacebookLoginButton/FacebookLoginButton.js
- src/Components/dashboard/Dashboard.js
- src/Components/dashboard/DashboardMenus/OrdersMenu.js
- src/i18n.js
- src/services/PayPal/PaypalCheckout.service.js
- src/utils/utils.js
This PR will change our i18n setup.
With the new feature, multilingual paywall. We're now supporting the detection and usage of a site language from the HTML `lang` attribute.
The first change needed was changing our region specified language keys eg. `en-US` to the general one `en`.
We're also observing any change to the HTML `lang` attribute and changing the UI language based on that. With a fallback to the default site language if the HTML lang isn't supported by our UI.
If you're using the exported `i18n.addResourceBundle`, you'll need to change the language key to the new keys we support.
Example:
before
```js
i18n.addResourceBundle(
"en-US",
"login",
{
messages: {
loginTo: "Login to your account",
},
},
true,
true
);
```
After
```js
i18n.addResourceBundle(
"en",
"login",
{
messages: …
```
> feat(i18n): use and observe page language in all UI

- src/Components/dashboard/Dashboard.js
- src/Components/dashboard/DashboardMenus/SubsMenu.js
- show the current active phase in the subscription phases sub-table
> feat(dashboard): add current phase to sub phases table

- src/Components/Register/RegisterView.js
- src/css/recaptcha.css
- src/index.css
- src/translations/en/messages.json
- src/translations/fr/messages.json
- hide global reCaptcha badge, and add copyright text instead. [relevant reCaptcha docs part](https://cloud.google.com/recaptcha-enterprise/docs/faq#id_like_to_hide_the_badge_what_is_allowed)
> feat(register): add copyright text and hide security badge

- src/Components/dashboard/DashboardMenus/SubsMenu.js
> fix(dashboard): sub with no phases showing empty phases table

- src/SubComponents/StripeElements.js
fix CVC and expiry date input not aligning properly if one of them has a long label that would wrap to a second line
> fix(paymentMethod): cvc and expiry date having incorrect alignment

- src/SubComponents/Phone.js
- fix phone field state sync issues causing inability to completely clear the phone field in order to remove your phone number.
> fix(edit profile modal): phone field can't be cleared

- src/Components/Register/RegisterModal.js
- src/Components/common/PelcroNativeButtons/saveToMetadata.js
- src/Components/dashboard/DashboardMenus/SubsMenu.js
- src/hooks/usePelcro/pelcroActions.js
- src/utils/utils.js
- stop unverified users from canceling or reactivating subs
- stop unverified users from saving articles to meta-data
- show verification modal after registration
> fix(customer verification): not stoping certain flows for unverified users

- src/Components/common/Helpers.js
- src/SubComponents/ConfirmPassword.js
- src/translations/en/common.json
- src/translations/fr/common.json
> fix(bugs): confirm pass lang FR & register error

- src/Components/UserUpdate/UserUpdateContainer.js
- src/Components/UserUpdate/UserUpdateEmail.js
- src/Components/UserUpdate/UserUpdateProfilePic.js
- src/Components/UserUpdate/UserUpdateView.js
> feat: send email field to the update profile function

- src/utils/utils.js
> fix: edit the isCurrencyZeroDecimal function to be case insensitive

- src/Components/AddressSelect/AddressSelectList.js
> fix(Address): Modal show only shipping addresses

- CHANGELOG.md
- src/Components/AddressSelect/AddressSelectList.js
- src/Components/SubscriptionCancel/SubscriptionCancelView.js
- src/Components/common/Auth0LoginButton/Auth0LoginButton.js
- src/Components/dashboard/DashboardMenus/SubsMenu.js
> fix: add cancel button to all subscriptions

- CHANGELOG.md
- src/Components/AddressSelect/AddressSelectList.js
- src/Components/SubscriptionCancel/SubscriptionCancelView.js
- src/Components/dashboard/DashboardMenus/SubsMenu.js
* fix: add cancel button to all active subscriptions
* fix: add cancel button to all active subscriptions (#164)
* fix: add cancel button to all active subscriptions
Co-authored-by: semantic-release-bot <semantic-release-bot@martynus.net>
* chore(release): 3.2.0-beta.43 [skip ci]
* add cancel button to all active subscriptions ([#164](https://github.com/pelcro-inc/react-pelcro-js/issues/164)) ([49514d5](https://github.com/pelcro-inc/react-pelcro-js/commit/49514d5721e733be9dc6e1fc853406bd85681ff7))
* fix: remove empty line
* fix: hide cancel button if already canceled at period end
* chore(release): 3.3.1-beta.1 [skip ci]
* add cancel button to all active subscriptions ([5311163](https://github.com/pelcro-inc/react-pelcro-js/commit/53111632320aa0626e510a4f9600696a49a23892))
* add cancel …
> fix: add cancel button to all subscriptions (#167)

- src/Components/Select/SelectModal.js
> fix(SelectModal): add (s) to print format

- src/Components/AddressSelect/AddressSelectContainer.js
> fix(SelectModal): id error

- src/Components/PaymentMethod/PaymentMethodContainer.js
- src/hooks/usePelcro/index.js
- src/hooks/usePelcro/pelcroActions.js
> feat(usePelcro): add setCouponCode and couponCode

- src/Components/PaymentMethod/PaymentMethodContainer.js
> refactor(PaymentMethod): remove SHOW_COUPON_FIELD

- src/Components/AddressCreate/AddressCreateContainer.js
- src/Components/AddressCreate/AddressCreateModal.js
- src/Components/AddressSelect/AddressSelectContainer.js
- src/Components/AddressSelect/AddressSelectModal.js
- src/Components/dashboard/DashboardMenus/MembershipsMenu.js
> fix(membership): UI issues

- CHANGELOG.md
- src/Components/SubscriptionCancel/SubscriptionCancelView.js
> fix: remove console log

- CHANGELOG.md
- src/Components/SubscriptionCancel/SubscriptionCancelView.js
> chore: merge master

- CHANGELOG.md
- src/Components/AddressSelect/AddressSelectContainer.js
> fix: check if no default address in the user show the select address modal

- src/Components/PaymentMethod/PaymentMethodView.js
https://app.asana.com/0/750497957484456/1202488057847159/f
> feat: hide google pay if vantiv gateway is enabled

- src/components.js
fixed minor issue by exporting QrCodeModal in component.js, which i missed previously
- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] Tested changes locally.
> fix: export QrCodeModal in components.js

- src/Components/dashboard/DashboardMenus/MembershipsMenu.js
> fix: hide membership if ended_at != null

- src/components.js
> fix: export QrCodeView in components.js

- src/Components/PaymentMethod/PaymentMethodContainer.js
> feat: update the custom CSS file name for Vantiv iframe

- src/Components/PaymentMethod/PaymentMethodContainer.js
> feat: edit Vantiv error messages

- src/Components/dashboard/DashboardMenus/MembershipsMenu.js
- src/translations/en/dashboard.json
- src/translations/fr/dashboard.json
- src/translations/ko/dashboard.json
> fix: membership edit address

- src/Components/dashboard/Dashboard.js
- src/assets/memberships.svg
- src/translations/en/dashboard.json
> fix: membership typo and icon

- src/Components/AddressCreate/AddressCreateCity.js
- src/Components/AddressCreate/AddressCreateFirstName.js
- src/Components/AddressCreate/AddressCreateLastName.js
- src/Components/AddressCreate/AddressCreatePostalCode.js
- src/Components/AddressCreate/AddressCreateView.js
- src/Components/dashboard/Dashboard.js
- src/SubComponents/StateSelect.js
> feat: edit the required fields in create address

- src/Components/InvoiceDetails/InvoiceDetailsView.js
> fix: change invoice details view to check if invoice is paid or not

- src/hooks/usePelcro/pelcroActions.js
> feat: add optional parameter to logout function

- src/Components/NewsLetter/NewsLetter.js
> feat: remove decrementPageViewFrequency

- src/Components/PaymentMethod/PaymentMethodContainer.js
> feat: edit the vantiv config to make the expiry date required

- public/index.html
- src/Components/GiftCreate/GiftCreateFirstName.js
- src/Components/GiftCreate/GiftCreateLastName.js
- src/Components/PaymentMethod/IncludeFirstName.js
- src/Components/PaymentMethod/IncludeLastName.js
- src/Components/PaymentMethod/IncludePhone.js
- src/Components/PaymentMethod/PaymentMethodContainer.js
- src/Components/PaymentMethod/PaymentMethodView.js
- src/Components/PaymentMethod/SubmitPaymentMethod.js
- src/Components/Register/RegisterButton.js
- src/Components/Register/RegisterView.js
- src/Components/UserUpdate/UserUpdateButton.js
- src/Components/UserUpdate/UserUpdateView.js
- src/translations/en/checkoutForm.json
- src/translations/fr/checkoutForm.json
- src/translations/ko/checkoutForm.json
> feat: add more required fields in the checkout view when tap is enabled

- src/Components/PelcroModalController/PelcroModalController.service.js
> fix: invoice url trigger with id

- src/Components/Login/LoginModal.js
- src/Components/PaymentMethod/PaymentMethodContainer.js
- src/Components/PelcroModalController/PelcroModalController.service.js
> fix: invoice url trigger

- src/Components/dashboard/DashboardMenus/SubsMenu.js
> feat: suspend/unsuspend button logic

- src/Components/Select/SelectModal.js
---
- https://app.asana.com/0/0/1203229897931764
> fix: from login if select empty go to register

- public/index.html
- src/Components/AddressSelect/AddressSelectContainer.js
- src/Components/AddressSelect/AddressSelectModal.js
> feat: free plan subscription

- src/Components/Register/RegisterContainer.js
> fix: display error on the UI "email in use"

- src/Components/Meter/MeterView.js
---
- https://app.asana.com/0/0/1203345446006131
> feat: add new meter design

- src/Components/common/PelcroNativeButtons/index.js
---
- https://app.asana.com/0/0/1203475317919524
> feat: add pelcro-dashboard-button

- src/Components/UserUpdate/UserUpdateContainer.js
- src/Components/UserUpdate/UserUpdateUsername.js
- src/Components/UserUpdate/UserUpdateView.js
- src/SubComponents/UpdateUserNameInput.js
- src/components.js
- src/translations/en/userEdit.json
- src/translations/es/userEdit.json
- src/translations/fr/userEdit.json
- src/translations/ko/userEdit.json
> feat: add update username in profile modal

- public/index.html
- src/Components/EmailVerify/EmailVerifyModal.js
- src/Components/Login/LoginModal.js
> fix: Purchase flow interruption when signing in or verifying email

- src/Components/Login/LoginModal.js
> fix: purchase flow URL trigger

- src/Components/Login/LoginModal.js
- src/Components/dashboard/Dashboard.js
- src/Components/dashboard/DashboardMenus/DonationsMenu.js
---
- https://app.asana.com/0/0/1201986628958227
> feat: cancel recurring donations

- src/Components/UserUpdate/UserUpdateView.js
- src/translations/en/userEdit.json
- src/translations/es/userEdit.json
- src/translations/fr/userEdit.json
- src/translations/ko/userEdit.json
---
- https://app.asana.com/0/0/1203570364216705
> feat(profile): add display name input

- src/Components/PaymentMethod/PaymentMethodContainer.js
---
- https://app.asana.com/0/0/1203588744886919
> fix: toggleAuthenticationSuccessPendingView fix

- src/Components/common/contentEntitlement/index.js
---
- https://app.asana.com/0/0/1203280511263087
> fix: blur/unblur entitlements

- src/Components/AddressCreate/AddressCreateView.js
- src/translations/en/address.json
- src/translations/es/address.json
- src/translations/fr/address.json
- src/translations/ko/address.json
> feat: change address create title when gifting

- src/Components/dashboard/DashboardMenus/AddressesMenu.js
- src/Components/dashboard/DashboardMenus/DonationsMenu.js
- src/Components/dashboard/DashboardMenus/GiftsMenu.js
- src/Components/dashboard/DashboardMenus/InvoicesMenu.js
- src/Components/dashboard/DashboardMenus/MembershipsMenu.js
- src/Components/dashboard/DashboardMenus/NewslettersMenu.js
- src/Components/dashboard/DashboardMenus/OrdersMenu.js
- src/Components/dashboard/DashboardMenus/PaymentCardsMenu.js
- src/Components/dashboard/DashboardMenus/ProfileMenu.js
- src/Components/dashboard/DashboardMenus/QRCodeMenu.js
- src/Components/dashboard/DashboardMenus/SavedItemsMenu.js
- src/Components/dashboard/DashboardMenus/SubsMenu.js
> fix: dashboard responsive

- .github/ISSUE_TEMPLATE/BUG.yml
- .github/ISSUE_TEMPLATE/config.yml
Add issue template and config.
> feat: issue template and config

- src/Components/SubscriptionManageMembers/SubscriptionManageMembersList.js
> fix: change class to className

- src/Components/dashboard/DashboardMenus/SubsMenu.js
> fix: subscription cancel button

- src/Components/EmailVerify/EmailVerifyModal.js
> fix: add missing import

- src/Components/EmailVerify/EmailVerifyModal.js
- src/Components/Login/LoginModal.js
- src/Components/Register/RegisterModal.js
> fix: purchase payment flow

- src/Components/dashboard/Dashboard.js
- src/translations/en/dashboard.json
- src/translations/es/dashboard.json
- src/translations/fr/dashboard.json
- src/translations/ko/dashboard.json
> fix: subscription after reactivation message

- src/Components/dashboard/Dashboard.js
- src/translations/en/dashboard.json
- src/translations/es/dashboard.json
- src/translations/fr/dashboard.json
- src/translations/ko/dashboard.json
> fix: extended subscription status

- package-lock.json
- package.json
- src/Components/PelcroModalController/PelcroModalController.service.js
- src/index.js
- src/utils/utils.js
- yarn.lock
> feat: add bugsnag to elements

- package-lock.json
- package.json
- src/Components/PelcroModalController/PelcroModalController.service.js
- src/index.js
- src/utils/utils.js
- yarn.lock
> fix: bugsnag edits

- src/utils/utils.js
> fix: comment MetaData

- src/Components/PelcroModalController/PelcroModalController.service.js
- src/utils/utils.js
> fix: comment notifyBugsnag

- src/Components/PelcroModalController/PelcroModalController.service.js
- src/utils/utils.js
> fix: move bugsnag notify

- src/Components/PelcroModalController/PelcroModalController.service.js
- src/utils/utils.js
> fix: bugsnag one metaData

- src/Components/PelcroModalController/PelcroModalController.service.js
- src/Components/Select/SelectModal.js
- src/utils/utils.js
> fix: move bugsnag to elect modal

- src/Components/PelcroModalController/PelcroModalController.service.js
- src/Components/Select/SelectModal.js
- src/index.js
- src/utils/utils.js
> fix: bugsnag selectModalMounted

- src/Components/PelcroModalController/PelcroModalController.service.js
- src/Components/Select/SelectModal.js
- src/index.js
- src/utils/utils.js
> fix: comment bugsnag selectModal

- package-lock.json
- package.json
- src/Components/PelcroModalController/PelcroModalController.service.js
- src/Components/Select/SelectModal.js
- src/index.js
- src/utils/utils.js
- yarn.lock
> fix: add bugsnag CDN

- src/Components/Select/SelectModal.js
- src/utils/utils.js
> feat: add bugsnag

- src/Components/Select/SelectModal.js
> fix: edits on bugsnag

- src/Components/PaymentMethod/PaymentMethodContainer.js
> fix: free plan using tap and vantiv

- src/Components/PaymentMethod/PaymentMethodContainer.js
> fix: send couponCode from URL if it's not set in state

- src/Components/SubscriptionManageMembers/SubscriptionManageMembersList.js
---
- https://app.asana.com/0/0/1203768703731882
> feat: membership email depending on status

- src/Components/PaymentMethod/PaymentMethodContainer.js
> feat: edit tap flow

- src/Components/PelcroModalController/PelcroModalController.service.js
---
- https://app.asana.com/0/0/1203976409818041
> fix: fixed payment-method-update url trigger issue

- src/Components/Select/SelectModal.js
> fix: metadata issue

- src/Components/Select/SelectModal.js
> fix: add methods and props effect products render

- src/Components/Select/SelectModal.js
> fix: bugsnag country_restrictions condition

- src/Components/PaymentMethod/PaymentMethodContainer.js
> fix: order price 0 submitPyment

- src/Components/Select/SelectModal.js
> fix: bugsnag fix currency

- src/Components/Login/LoginModal.js
- src/Components/PelcroModalController/PelcroModalController.service.js
> fix: iframe crash payment

- CHANGELOG.md
- src/Components/PaymentMethod/PaymentMethodContainer.js
- src/Components/SubscriptionManageMembers/SubscriptionManageMembersList.js
> fix: manage members email invitation

- src/Components/OrderCreate/OrderCreateFreeButton.js
- src/Components/OrderCreate/OrderCreateView.js
- src/Components/PaymentMethod/PaymentMethodContainer.js
- src/Components/PaymentMethod/PaymentMethodView.js
- src/Components/PaymentMethodSelect/PaymentMethodSelectModal.js
- src/Components/dashboard/Dashboard.js
- src/Components/dashboard/DashboardMenus/InvoicesMenu.js
- src/components.js
- src/translations/en/checkoutForm.json
- src/translations/es/checkoutForm.json
- src/translations/fr/checkoutForm.json
- src/translations/ko/checkoutForm.json
- src/utils/utils.js
> fix: allow e commerce orders for 0

- package-lock.json
- package.json
- src/Components/PaymentMethodUpdate/PaymentMethodUpdateModal.js
- src/Components/PelcroModalController/PelcroModalController.service.js
- src/Components/Register/RegisterModal.js
- src/Components/Select/SelectModal.js
- src/Components/SubscriptionCancel/SubscriptionCancelLaterButton.js
- src/Components/SubscriptionCancel/SubscriptionCancelNowButton.js
- src/Components/SubscriptionRenew/SubscriptionRenewModal.js
- src/Components/SubscriptionSuspend/SubscriptionSuspendButton.js
- src/Components/common/PelcroNativeButtons/saveToMetadata.js
- src/Components/dashboard/Dashboard.js
- src/Components/dashboard/DashboardMenus/SavedItemsMenu.js
- src/SubComponents/Logout.js
- src/hooks/usePelcro/pelcroActions.js
- src/utils/utils.js
- yarn.lock
> feat: use ReactGA4

- src/SubComponents/CountrySelect.js
- src/SubComponents/StateSelect.js
- src/utils/utils.js
> fix: US,CA sorting to top of list

- src/Components/PelcroModalController/PelcroModalController.service.js
- Fix ReactGA initialisation bug
> fix: initialise reactga bug fix

- src/Components/SubscriptionCancel/SubscriptionCancelOptions.js
> feat: add comment

- src/Components/PelcroModalController/PelcroModalController.service.js
Fixed race condition on loading paywalls without user details fetched
---
- https://app.asana.com/0/0/1205045334341460
> fix: Fix load paywalls race condition

- src/Components/Cart/CartRemoveItemButton.js
- Fix cart remove item button display bug on safari
> fix: cart remove item button display bug on safari

- src/Components/ApplePayButton/ApplePayButton.js
- Add production eProtectRequestURL
> feat: add prod eProtectRequestURL

- src/Components/PelcroModalController/PelcroModalController.service.js
- Upgrade jquery to version 3.6.3
> feat: upgrade jquery to version 3.6.3 from 1.4.2

- src/Components/dashboard/Dashboard.js
- src/Components/dashboard/DashboardMenus/MembershipsMenu.js
- Change displaying memberships filter
> fix: change the filter for displaying memberships

- src/Components/PaymentMethod/PaymentMethodContainer.js
- Support 3DS2 flow in payment method actions
> feat: support 3ds2 in payment method actions

- src/Components/PaymentMethod/PaymentMethodContainer.js
- Persist button loading until 3DS2 success
> feat: persist button loading until 3ds2 success

- src/Components/PaymentMethod/PaymentMethodContainer.js
- support 3DS2 in trail subscriptions
> feat: support 3ds2 in trail subs

- src/Components/PasswordForgot/PasswordForgotContainer.js
- src/Components/PasswordReset/PasswordResetContainer.js
- Add referer attribute to password endpoints
> feat: add referer attribute to password endpoints

- src/Components/OrderCreate/OrderCreateSummary.js
- Consume `window.Pelcro.ecommerce.order.createSummary` in order to display `subtotal`, `shippingRate`  and `total`.
> feat: order create modal shipping rate

- src/Components/Select/SelectModal.js
- src/SubComponents/Carousel.js
https://github.com/pelcro-inc/react-pelcro-js/pull/371
> feat: display carousel for items length at least 2 (#371)

- src/Components/Select/SelectModal.js
Reverts pelcro-inc/react-pelcro-js#374
> Revert "Feat/select modal carousel for plans"

- src/Components/PaymentMethod/PaymentMethodContainer.js
- src/Components/PaymentMethod/PaymentMethodView.js
- src/Components/PelcroModalController/PelcroModalController.service.js
- src/SubComponents/StripeElements.js
> feat: Fixing Braintree/Stripe Bug

- src/Components/PaymentMethod/PaymentMethodContainer.js
- src/Components/PaymentMethod/SelectedPaymentMethod.js
Refresh user data after adding new braintree card
> feat: New Card Handling

- src/Components/OrderCreate/OrderCreateSummary.js
- src/Components/PaymentMethodSelect/PaymentMethodSelectContainer.js
- src/translations/en/shop.json
- src/utils/utils.js
> feat: add tax to order summary

- package-lock.json
- package.json
- yarn.lock
> feat: downgrade axios

- src/Components/Select/SelectModal.js
> feat: clear itemId when selecting different plan

- src/Components/PelcroModalController/PelcroModalController.js
- src/Components/PelcroModalController/PelcroModalController.service.js
Allow for passing customOptions to disable page view events
> feat: allow to disable page view events

- src/Components/Select/SelectModal.js
Adding a prop for hiding gift button from the select modal
> feat: add prop for hiding gift button

- src/Components/Register/RegisterView.js
> feat: require name fields

- src/Components/Register/RegisterView.js
> feat: uisetting for requiring name fields

- src/Components/Register/RegisterView.js
> feat: alpha_register_required_field_ui_settings

- src/Components/Cart/CartContainer.js
- src/Components/common/PelcroNativeButtons/index.js
> remove-currency-mismatch

- src/hooks/usePelcro/pelcroActions.js
> feat: fix match user account

- src/Components/GiftRedeem/GiftRedeemContainer.js
- src/Components/Register/RegisterModal.js
> fix: preserve gift code during registration flow to prevent re-entry

- src/Components/dashboard/Dashboard.js
- src/Components/dashboard/EmailPreferencesMenu.js
- src/translations/en/dashboard.json
- src/translations/fr/dashboard.json
add a new dropdown "Email Notifications" if emailNotifications: true in the uiSettings.
> feat: email notifcations dropdown in dashboard

- public/index.html
- src/Components/PaymentMethod/PaymentMethodContainer.js
- src/services/Subscription/Payment.service.js
> feat: add_cybersource

- src/Components/common/Auth0LoginButton/Auth0LoginButton.js
- src/Components/common/FacebookLoginButton/FacebookLoginButton.js
- src/Components/common/GoogleLoginButton/GoogleLoginButton.js
- src/translations/en/login.json
- src/translations/en/register.json
- src/translations/es/login.json
- src/translations/es/register.json
- src/translations/fr/login.json
- src/translations/fr/register.json
- src/translations/ko/login.json
- src/translations/ko/register.json
> feat: Handle login Auth when email not found
