src/Components/ProfilePicChange/ProfilePicChangeContainer.js, src/translations/en/userEdit.json, src/translations/fr/userEdit.json
- fix alert now showing up after successfully updating user's profile picture
=> fix(profile picture): success alert not showing up

src/hooks/usePelcro/index.js, src/utils/utils.js
- fix [gift recipient field not getting reset when resetState is called](https://app.asana.com/0/1199393268587978/1200561514293003)
- fix [analytics not showing gifted subscriptions as e-commerce transactions](https://app.asana.com/0/1199393268587978/1200450203940475)
- [] Added a changelog entry.
=> fix(usePelcro): gift recipient field not getting reset when resetState is called

src/Components/PelcroModalController/PelcroModalController.service.js, src/SubComponents/Modal.js
When a modal is viewed, we should trigger a JS event called PelcroModalDisplay. I should expect to listen to it as such:
window.addEventListener('PelcroModalDisplay', (e) => e.detail.modalName)
where modalName is the name of the modal that we are using. For example, 'OrderConfirmModal' will trigger a view event with modalName='OrderConfirmModal'.
```js
document.addEventListener('PelcroModalDisplay', (e) => {
console.log(e.detail.modalName)
});
```
=> feat: dispatch modal view event with each modal displayed

src/SubComponents/StripeElements.js
- fix credit cards image in checkout form not having an explicitly set width.
=> fix(checkout form): credit cards icons having no explicit width

src/Components/dashboard/Dashboard.js
- fix dashboard close button not being visible on Safari
=> fix(dashboard): close button not visible on Safari

src/Components/dashboard/Dashboard.js
- fix overflowing plan name text under gifts and subscriptions sections
=> fix(dashboard): plan text overflow

CHANGELOG.md, src/Components/AddressCreate/AddressCreateContainer.js, src/Components/AddressCreate/AddressCreateModal.js, src/Components/AddressSelect/AddressSelectContainer.js, src/Components/AddressSelect/AddressSelectModal.js, src/Components/PaymentSuccess/PaymentSuccessView.js, src/Components/SubscriptionCreate/SubscriptionCreateModal.js, src/Components/dashboard/Dashboard.js, src/SubComponents/Notification.css, src/SubComponents/Notification.js, src/i18n.js, src/translations/en/dashboard.json, src/translations/en/notification.json, src/translations/en/success.json, src/translations/fr/dashboard.json, src/translations/fr/notification.json, src/translations/fr/success.json
This PR changes 4 main things
PS. French wording is not final yet. Waiting on that before closing the PR
Gift creation success
Gift redeem success
Cancelation flow
Happy scenario 
https://user-images.githubusercontent.com/6924756/135347919-c448f38f-6186-40cc-9f78-a5ee3eae0edd.mp4
Failure scenario
https://user-images.githubusercontent.com/6924756/135347890-d446285b-971e-41c9-925c-338af6c57448.mp4
=> feat(gift create and redeem):use payment success modal not native alerts

src/Components/Login/LoginView.js, src/Components/PaymentSuccess/PaymentSuccessView.js, src/Components/dashboard/Dashboard.js, src/translations/en/notification.json, src/translations/fr/dashboard.json, src/translations/fr/notification.json, src/translations/fr/success.json
This PR includes a change in the dashboard UI where we're using current_period_end instead of the actual expiry date of the sub.
This fixes that and also adds some missing French wording.
=> feat(dashboard): use phase sensitive dates in subscription section

package.json, rollup.config.js, src/Components/PelcroModalController/PelcroModalController.service.js, yarn.lock
this is simply #99 done again after getting reverted, the only difference here is that we're now loading the SDK when the user is authenticated instead of loading it when payment modals are opened
=> feat: lazy load Stripe SDK

src/Components/GiftCreate/GiftCreateContainer.js, src/utils/utils.js
This PR fixes a bug with a false positive regarding time comparison on gift creation.
=> fix(gift creation): error dispatched if gift date is set to today

src/Components/PelcroModalController/PelcroModalController.js, src/Components/PelcroModalController/PelcroModalController.service.js, src/Components/Register/RegisterButton.js, src/Components/Register/RegisterContainer.js
this is part of our second security token experiment, the goal is to move the logic from the SDK to the elements to see if this would solve the problem of getting incorrect assessments.
- Load security SDK if the site does have a proper `security_key` value as part of the GET site API call
- Add security token generation logic to the register container
=> feat: add expiremental security token support

src/Components/Select/SelectModal.js, src/translations/en/select.json, src/translations/fr/select.json
A problem that we have with the tagged paywall feature is the user will have no idea which product to subscribe to if they are paywalled on an article, which product will unlock this article? 
This PR adds an approach to emphasize the products/plans which will unlock the article:
"Subscribe to one of the following options to get access to this page"
Product A
Product B
—————————————————
"Or take a look at some of our other options below:"
Product C
In case there is no matching product, we render the normal product list.
=> feat(select modal): emphasize a product if it matches page tag

src/Components/Register/RegisterContainer.js
- fix a bug where sites that already use grecaptcha are being treated as sites that use pelcro's grecaptcha integration even if they don't
=> fix(register): failing if site already uses grecaptcha outside pelcro

src/Components/PaymentMethod/PaymentMethodContainer.js, src/Components/PaymentMethod/PaymentMethodView.js, src/Components/PaymentMethodCreate/PaymentMethodCreateView.js, src/Components/PaymentMethodUpdate/PaymentMethodUpdateSetDefault.js, src/Components/PaymentMethodUpdate/PaymentMethodUpdateView.js
- Adding prop hiddenSetAsDefaul for PaymentMethodUpdateModal  to be able to set any updated card as default without showing set as default check box.
=> feat: Add hidden setAsDefault

src/Components/Select/SelectModal.js, src/SubComponents/ImageSelect.js
Added `hideGiftSelection` props to the Select Modal. When true the dropdown for selecting gift is not present
Fixed with of the select gift menu
=> feat: add hideGiftSelection prop to SelectModal

src/Components/Select/SelectModal.js, src/SubComponents/Carousel.js
- Update the logic of `select-modal` so that it displays items in a carousel when there are at least 2 items, instead of 3 as it did previously.
=> feat: display carousel for items length at least 2

src/SubComponents/ImageSelect.css, src/SubComponents/ImageSelect.js
Bring back old font for `ImageSelectOptions`
Before:
After:
=> fix: image select options font change

src/Components/Select/SelectModal.js
Added a new setting hideGiftForAutoRenew that hides the gift button for auto-renewing plans when enabled. The gift button will still show for non-auto-renewing plans.
=> feat: hideGiftForAutoRenew prop

src/Components/Login/LoginModal.js, src/Components/PelcroModalController/PelcroModalController.service.js, src/Components/Register/RegisterModal.js
showing redeem modal only once when not logged in.
=> feature: only show redeem modal only once

src/Components/PaymentMethodSelect/PaymentMethodSelectContainer.js
This PR fixes an issue where the payment method selection component throws a "Cannot read properties of undefined (reading 'id')" error when no default payment method exists. The error occurs in the `moveDefaultPaymentMethodToStart` function when trying to filter payment methods using a non-existent default payment method.
- Added null check for default payment method before filter operation
- Return original payment methods array when no default exists
- Maintain original behavior for cases where default payment method exists
- Verified that the component works when:
- User has a default payment method
- User has payment methods but none are default
- User has no payment methods
- [] Updated documentation.
N/A - This is a bug fix with no UI changes
=> fix: handle undefined default payment method
